### ISSUE TITLE
No release?

### ISSUE THREAD

**Issue by AnsonEyre** [Jaskowicz1/fdr-remake#1]
In the installation instructions, it says:

> ...
Download the latest executable from the releases tab.
...

I couldn't find any releases. Am I missing something?

**Comment by Jaskowicz1** [comment]
Hi there! Nope, that's on me, sorry about that! I'll get it fixed up super soon.

**Comment by Jaskowicz1** [comment]
Hi there! Sorry for the major delay, been busy :sweat_smile:

I've released the latest executable now for you! https://github.com/Jaskowicz1/fdr-remake/releases/tag/v1.0.0

Windows binaries will be up in ~24 hours!
